apiVersion: v1
kind: Namespace
metadata:
  name: llama-1b-demo
---
apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: llama-3-2-1b-instruct
  namespace: llama-1b-demo
spec:
  predictor:
    model:
      baseModel: llama-3-2-1b-instruct
      protocolVersion: openAI
    minReplicas: 1
    maxReplicas: 1
