apiVersion: v1
kind: Namespace
metadata:
  name: qwen-1-5b-demo
---
apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: qwen2-5-1-5b-instruct
  namespace: qwen-1-5b-demo
spec:
  predictor:
    model:
      baseModel: Qwen/Qwen2.5-1.5B-Instruct
      protocolVersion: openAI
      runtime: sglang
      runtimeArgs:
        - --kv-cache-dtype
        - int4
    minReplicas: 1
    maxReplicas: 1
