apiVersion: v1
kind: Namespace
metadata:
  name: rustfs

---
apiVersion: v1
kind: Secret
metadata:
  name: rustfs-secrets
  namespace: rustfs
type: Opaque
stringData:
  # Change these in production!
  access-key: "admin"
  secret-key: "password"
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustfs-data
  namespace: rustfs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-zfs
  resources:
    requests:
      storage: 1Ti
