#!/bin/bash
# resize-swap.sh -- drop the 128 GiB swapfile on nimbus, keep the 16 GiB default.
#
# WHY (incident 2026-08-24): nimbus has 121 GiB of RAM and had 143 GiB of swap.
# The kernel OOM killer only fires when reclaim AND swap both fail to make
# progress. With 143 GiB of swap sitting free, that condition is effectively
# unreachable -- so instead of reaping the runaway vLLM pod, the kernel swapped
# out every *other* process on the box and thrashed until the GPU driver
# deadlocked. Oversized swap did not protect this machine, it prevented the one
# mechanism that would have.
#
# Keeping /swap.img (16 GiB, the Ubuntu default) preserves a cushion for genuine
# cold anonymous pages and Jupyter bursts, at a ratio where OOM can still fire.
#
# Safety:
#   - Verified hibernation is NOT available on this host (/sys/power/disk empty,
#     no resume= on the kernel cmdline), so no swap>=RAM requirement applies.
#   - Refuses to run if the swapfile is actually in use beyond what RAM can absorb.
#   - swapoff migrates any in-use pages back to RAM before the file is removed.

set -euo pipefail
[ "$EUID" -eq 0 ] || { echo "must run as root (use sudo)" >&2; exit 1; }

TARGET=/swapfile128

[ -e "$TARGET" ] || { echo "$TARGET does not exist -- nothing to do."; exit 0; }

echo "==> current swap:"
swapon --show
echo
free -h | head -2
echo

# --- refuse if hibernation is configured -----------------------------------
if grep -q 'resume=' /proc/cmdline 2>/dev/null || [ -s /etc/initramfs-tools/conf.d/resume ]; then
    echo "ABORT: hibernation appears to be configured; swap sizing may be load-bearing." >&2
    exit 1
fi

# --- refuse if the pages could not fit back into RAM -----------------------
USED_KIB=$(awk -v t="$TARGET" '$1==t {print $4}' /proc/swaps)
AVAIL_KIB=$(awk '/^MemAvailable:/ {print $2}' /proc/meminfo)
echo "==> $TARGET currently holds $((USED_KIB/1024)) MiB; MemAvailable is $((AVAIL_KIB/1024)) MiB"
if [ "$USED_KIB" -gt $((AVAIL_KIB * 80 / 100)) ]; then
    echo "ABORT: swapoff would need to fault in $((USED_KIB/1024)) MiB but only" >&2
    echo "       $((AVAIL_KIB/1024)) MiB is available. Free memory first." >&2
    exit 1
fi

# --- do it ------------------------------------------------------------------
echo "==> swapoff $TARGET (this can take a while if pages must be faulted back in)"
swapoff "$TARGET"

echo "==> removing $TARGET from /etc/fstab"
cp -a /etc/fstab "/etc/fstab.bak-$(date +%Y%m%d-%H%M%S)"
sed -i "\|^${TARGET}[[:space:]]|d" /etc/fstab

echo "==> deleting $TARGET (reclaims 128 GiB of disk)"
rm -f "$TARGET"

# swapfile128.swap was generated by systemd-fstab-generator; regenerate units.
systemctl daemon-reload

echo
echo "==> done. new state:"
swapon --show
free -h | head -2
