FROM ghcr.io/rocker-org/cuda

# Config will be populated by env vars and moved to HOME via start script: (hub-dependent)
COPY continue/config.json /opt/share/continue/config.json
COPY continue/config.ts /opt/share/continue/config.ts

RUN /opt/venv/bin/pip install \
    huggingface_hub \
    nox \
    nvitop \
    plotnine \
    PyYaml \
    pytest \
    scikit-optimize \
    "ray[rllib,tune]" \
    huggingface_sb3 \
    stable-baselines3 \
    sb3-contrib


