FROM  quay.io/jupyter/datascience-notebook:2024-05-27

COPY jupyter-env.yml /tmp/environment.yml
RUN conda env update -n base -f /tmp/environment.yml

## this stack uses tini as default entrypoint.  run with --entrypoint="" for default (e.g. root) shell.


