#https://github.com/isaacbrodsky/h3-duckdb

FROM ubuntu
ARG nproc=24

RUN apt-get update && apt-get -y install git cmake ninja-build build-essential python3-dev

RUN git clone https://github.com/isaacbrodsky/h3-duckdb && cd h3-duckdb && \
    git submodule update --init && GEN=ninja make release

CMD /h3-duckdb/build/release/duckdb -unsigned
#RUN mkdir build && \ 
#    cd build && CMAKE_BUILD_PARALLEL_LEVEL=$(nproc) cmake .. && \
#    cd .. && ./build/release/duckdb -unsigned

