apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${USERID}-binding
  namespace: ${USERID}
subjects:
- kind: ServiceAccount
  name: ${USERID}
  namespace: ${USERID}
roleRef:
  kind: Role
  name: ${USERID}-role
  apiGroup: rbac.authorization.k8s.io
