githubConfigUrl: "https://github.com/eco4cast"
githubConfigSecret:
  #github_app_id: ""
  #github_app_installation_id: ""
  #github_app_private_key: |
  ### OR USE GitHub PAT Configuration
  # github_token: ""
maxRunners: 1
runnerGroup: "default"

## Container mode is an object that provides out-of-box configuration
## for dind and kubernetes mode. Template will be modified as documented under the
## template object.
##
## If any customization is required for dind or kubernetes mode, containerMode should remain
## empty, and configuration should be applied to the template.
# containerMode:
#   type: "dind"  ## type can be set to dind or kubernetes
## template is the PodSpec for each runner Pod
## For reference: https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#PodSpec
template:
  ## template.spec will be modified if you change the container mode
  ## with containerMode.type=dind, we will populate the template.spec with following pod spec
   template:
     spec:
       initContainers:
       - name: init-dind-externals
         image: ghcr.io/actions/actions-runner:latest
         command: ["cp", "-r", "-v", "/home/runner/externals/.", "/home/runner/tmpDir/"]
         volumeMounts:
           - name: dind-externals
             mountPath: /home/runner/tmpDir
       containers:
       - name: runner
         image: ghcr.io/actions/actions-runner:latest
         command: ["/home/runner/run.sh"]
         requests:
           memory: 20.0Gi
         limits:
           memory: 60.0G
         env:
           - name: DOCKER_HOST
             value: unix:///var/run/docker.sock
         volumeMounts:
           - name: work
             mountPath: /home/runner/_work
           - name: dind-sock
             mountPath: /var/run
       - name: dind
         image: docker:dind
         args:
           - dockerd
           - --host=unix:///var/run/docker.sock
           - --group=$(DOCKER_GROUP_GID)
         env:
           - name: DOCKER_GROUP_GID
             value: "123"
         securityContext:
           privileged: true
         volumeMounts:
           - name: work
             mountPath: /home/runner/_work
           - name: dind-sock
             mountPath: /var/run
           - name: dind-externals
             mountPath: /home/runner/externals
       volumes:
       - name: work
         emptyDir: {}
       - name: dind-sock
         emptyDir: {}
       - name: dind-externals
         emptyDir: {}

