apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpt-oss
  labels:
    k8s-app: vllm-nimbus
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: vllm-nimbus
  template:
    metadata:
      labels:
        k8s-app: vllm-nimbus
    spec:
      runtimeClassName: nvidia
      containers:
      - name: vllm
        image: nvcr.io/nvidia/vllm:25.09-py3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: TIKTOKEN_ENCODINGS_BASE
          value: /etc/encodings
        - name: HF_HOME
          value: /models
        - name: TRANSFORMERS_CACHE
          value: /models/hub
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: huggingface-token
              key: token
              optional: true
        - name: VLLM_API_KEY
          valueFrom:
            secretKeyRef:
              name: vllm-api-key
              key: api-key
        - name: VLLM_LOGGING_LEVEL
          value: "DEBUG"
        args:
        - "vllm"
        - "serve"
        - "openai/gpt-oss-120b"
        - "--served-model-name"
        - "nimbus"
        - "--gpu-memory-utilization"
        - "0.7"
        volumeMounts:
        - name: encodings
          mountPath: /etc/encodings
          readOnly: true
        - name: dshm
          mountPath: /dev/shm
        - name: model-volume
          mountPath: /models
          readOnly: false
        resources:
          requests:
            cpu: 8
            memory: 32Gi
            nvidia.com/gpu: 1
          limits:
            cpu: 8
            memory: 32Gi
            nvidia.com/gpu: 1
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
      volumes:
      - name: encodings
        hostPath:
          path: /home/cboettig/Documents/github/boettiger-lab/k8s/vllm/nimbus/gpt-oss/encodings
          type: Directory
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 1Gi
      - name: model-volume
        persistentVolumeClaim:
          claimName: vllm-pvc
