singleuser:
  lifecycleHooks:
    postStart:
      exec:
        command: ["/bin/bash", "-c", "mkdir -p $XDG_DATA_HOME/jupyter/jupyter_ai && wget -q https://github.com/boettiger-lab/k8s/raw/refs/heads/main/images/jupyter_ai/config.json -O - | envsubst > $XDG_DATA_HOME/jupyter/jupyter_ai/config.json"]

