# This file can update the JupyterHub Helm chart's default configuration values.
#
# For reference see the configuration reference and default values, but make
# sure to refer to the Helm chart version of interest to you!
#
# Introduction to YAML:     https://www.youtube.com/watch?v=cdLNKUoMc6c
# Chart config reference:   https://zero-to-jupyterhub.readthedocs.io/en/stable/resources/reference.html
# Chart default values:     https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/HEAD/jupyterhub/values.yaml
# Available chart versions: https://hub.jupyter.org/helm-chart/
ingress:
  enabled: true
proxy:
  service:
    type: NodePort
cull:
  enabled: false
singleuser:
  image: 
    pullPolicy: Always
  storage:
    capacity: 60Gi
    extraVolumeMounts:
      - name: "volume-{username}{servername}"
        mountPath: /home/rstudio
#      - name: shm-volume
#        mountPath: /dev/shm
#    extraVolumes:
#      - name: shm-volume
#        emptyDir:
#          medium: Memory
  profileList:
    - display_name: "CPU"
      slug: rocker
      description: R environment with many geospatial libraries pre-installed
      profile_options: &profile_options 
        resource_allocation: &profile_options_resource_allocation 
          display_name: Resource Allocation
          choices:
            small:
              display_name: Small (8 GB RAM)
              kubespawner_override:
                mem_guarantee: 7991341312
                mem_limit: 7991341312
            med:
              display_name: Medium (16 GB RAM)
              kubespawner_override:
                mem_guarantee: 15930730496
                mem_limit: 15930730496
              default: true
            large:
              display_name: Large (30 GB RAM)
              kubespawner_override:
                mem_guarantee: 29861460992
                mem_limit: 29861460992
      kubespawner_override:
        image: "zcr.thelio.carlboettiger.info/boettiger-lab/k8s:latest"
        default_url: /lab # change to /rstudio to go straight to RStudio
        working_dir: /home/rstudio
    - display_name: "GPU"
      slug: gpu
      description: Jupyter + R with GPU 
      default: true
      allowed_teams:
        - espm-288:jupyterhub
      profile_options:
        resource_allocation: *profile_options_resource_allocation 
      kubespawner_override:
        image: "zcr.thelio.carlboettiger.info/boettiger-lab/k8s-gpu:latest"
        default_url: /lab # change to /rstudio to go straight to RStudio
        working_dir: /home/rstudio
    - display_name: "NASA Image"
      slug: pangeo
      description: Pangeo 
      profile_options:
        resource_allocation: *profile_options_resource_allocation 
      kubespawner_override:
        image: "zcr.thelio.carlboettiger.info/boettiger-lab/nasa-tops:latest"
    - display_name: "Bring your own image"
      description: Specify your own docker image (must have python and jupyterhub installed in it)
      slug: custom
      profile_options:
        image:
          display_name: Image
          unlisted_choice:
            enabled: True
            display_name: "Custom image"
            kubespawner_override:
              image: "{value}"
          choices: {}
hub:
  config:
    # Shared settings. we don't need nvidia to be default
    KubeSpawner:
      environment:
        SHELL: /usr/bin/bash
        GH_SCOPED_CREDS_CLIENT_ID: "Iv1.8d384d9612c2ecc3"
        GH_SCOPED_CREDS_APP_URL: "https://github.com/apps/jupyterhub-gh-creds"
      extra_pod_config:
        runtimeClassName: "nvidia"
    Authenticator:
      admin_users:
        - cboettig
      allowed_users:
        - mlap
    GitHubOAuthenticator:
      enable_auth_state: true
      populate_teams_in_auth_state: true
      allowed_organizations:
        - espm-288:jupyterhub
        - boettiger-lab:current-members
      scope:
        - read:org
      oauth_callback_url: https://jupyterhub.thelio.carlboettiger.info/hub/oauth_callback
    JupyterHub:
      authenticator_class: github

