# This file can update the JupyterHub Helm chart's default configuration values.
#
# For reference see the configuration reference and default values, but make
# sure to refer to the Helm chart version of interest to you!
#
# Introduction to YAML:     https://www.youtube.com/watch?v=cdLNKUoMc6c
# Chart config reference:   https://zero-to-jupyterhub.readthedocs.io/en/stable/resources/reference.html
# Chart default values:     https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/HEAD/jupyterhub/values.yaml
# Available chart versions: https://hub.jupyter.org/helm-chart/
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: traefik
  tls:
  - hosts:
    - jupyterhub.thelio.carlboettiger.info
    secretName: jupyter-thelio-tls
cull:
  enabled: false
singleuser:
  image: 
    pullPolicy: Always
  storage:
    type: dynamic
    extraLabels: {}
    capacity: 60Gi
    homeMountPath: /home/jovyan
    dynamic:
      storageClass:  openebs-zfs
      pvcNameTemplate: claim-{escaped_user_server}
      volumeNameTemplate: volume-{escaped_user_server}
      storageAccessModes: [ReadWriteOnce]
    extraVolumeMounts:
      - name: shm-volume
        mountPath: /dev/shm
    extraVolumes:
      - name: shm-volume
        emptyDir:
          medium: Memory
  extraFiles:
    # mounts containing folder as read-only
    jupyter_server_config.json:
        mountPath: /usr/local/etc/jupyter/jupyter_server_config.json
        data:
          # Allow JupyterLab to show the 'View -> Show Hidden Files' option
          # in the menu. Defaults are not changed.
          # https://github.com/jupyterlab/jupyterlab/issues/11304#issuecomment-945466766
          ContentsManager:
            allow_hidden: true
          FileContentsManager:
            always_delete_dir: true
  profileList:
    - display_name: "Choose your environment and resources"
      default: true
      profile_options:
        image:
          display_name: Environment
          dynamic_image_building:
            enabled: True
          unlisted_choice:
            enabled: True
            display_name: "Custom image"
            display_name_in_choices: "Specify an existing docker image"
            description_in_choices: "Use a pre-existing docker image from a public docker registry"
            description: Specify your own docker image (must have python and jupyterhub installed in it)
            validation_regex: "^.+:.+$"
            validation_message: "Must be a publicly available docker image, of form <image-name>:<tag>"
            kubespawner_override:
              image: "{value}"
          choices:
            02-cpu:
              display_name: CPU 
              description: General purpose python + R (with RStudio) environment 
              kubespawner_override:
                image:  "ghcr.io/boettiger-lab/k8s:latest"
            01-gpu:
              display_name: GPU
              description: CUDA GPU environment, with spatial-GPU 
              kubespawner_override:
                image: "ghcr.io/rocker-org/cuda-spatial:latest"
                default_url: "/vscode"
        resource_allocation:
          display_name: Resource Allocation
          choices:
            small:
              display_name: 8 GB RAM
              kubespawner_override:
                mem_guarantee: 8G
                mem_limit: 8G
            big:
              display_name: 45 GB RAM
              kubespawner_override:
                mem_guarantee: 45G
                mem_limit: 45G 
              default: true

hub:
  allowNamedServers: true
  namedServerLimitPerUser: 1
  config:
    # Shared settings. we don't need nvidia to be default
    KubeSpawner:
      environment:
        SHELL: /usr/bin/bash
        GH_SCOPED_CREDS_CLIENT_ID: "Iv1.8d384d9612c2ecc3"
        GH_SCOPED_CREDS_APP_URL: "https://github.com/apps/jupyterhub-gh-creds"
        AWS_S3_ENDPOINT: "minio.carlboettiger.info"
        AWS_HTTPS: "true"
      extra_pod_config:
        runtimeClassName: "nvidia"
    Authenticator:
      admin_users:
        - cboettig
    GitHubOAuthenticator:
      enable_auth_state: true
      populate_teams_in_auth_state: true
      allowed_organizations:
        - boettiger-lab:current-members
      scope:
        - read:org
      oauth_callback_url: https://jupyterhub.thelio.carlboettiger.info/hub/oauth_callback
    JupyterHub:
      authenticator_class: github
  services:
    binder:
      url: http://binderhub
  image:
    name: quay.io/yuvipanda/z2jh-hub-with-fancy-profiles
    tag: z2jh-v4.0.0-fancy-profiles-sha-f80b661      
  extraConfig:
    enable-fancy-profiles: |
      from jupyterhub_fancy_profiles import setup_ui
      setup_ui(c)

