# cluster-issuer-production.yaml
# Updated to use DNS-01 challenge with Cloudflare (Jan 2026)
# This fixes certificate renewal issues with HTTP-01 challenges

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: default
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: cboettig@gmail.com 
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - selector: {}
      dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cf-api-token
            key: CF_API_TOKEN
