name: Docker Image CI
on:
  workflow_dispatch: null
  push:
    paths: ['images/*']
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        if: github.repository == 'boettiger-lab/k8s'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build the Docker image
        if: github.repository == 'boettiger-lab/k8s'
        run: docker build images/ -f images/Dockerfile.gpu --tag ghcr.io/boettiger-lab/k8s-gpu:latest
      - name: Publish
        if: github.repository == 'boettiger-lab/k8s'
        run: docker push ghcr.io/boettiger-lab/k8s-gpu:latest

